const players = [
    {
        name: "Rohit Sharma",
        country: "Us",
        type: "Batsman",
        prevTeam: "Harsh",
        iplTeam: "MI",
        fp: 527,
        bp: 2,
    },
    {
        name: "Shubman Gill",
        country: "Aus",
        type: "Batsman",
        prevTeam: "Hardik",
        iplTeam: "GT",
        fp: 1305,
        bp: 2,
    },
    {
        name: "Virat Kohli",
        country: "India",
        type: "Batsman",
        prevTeam: "Hardik",
        iplTeam: "RCB",
        fp: 1000,
        bp: 2,
    },
    {
        name: "KL Rahul",
        country: "India",
        type: "W/K",
        prevTeam: "Rishabh",
        iplTeam: "LSG",
        fp: 402,
        bp: 2,
    },
    {
        name: "Ishan Kishan",
        country: "Australia",
        type: "W/K",
        prevTeam: "Durvesh",
        iplTeam: "MI",
        fp: 814,
        bp: 2,
    },
    {
        name: "Hardik Pandya",
        country: "India",
        type: "All Rounder",
        prevTeam: "Aditya",
        iplTeam: "GT",
        fp: 527,
        bp: 2,
    },
    {
        name: "Ravindra Jadeja",
        country: "India",
        type: "All Rounder",
        prevTeam: "Dev",
        iplTeam: "CSK",
        fp: 945,
        bp: 2,
    },
    {
        name: "Shardul Thakur",
        country: "India",
        type: "Bowler",
        prevTeam: "Durvesh",
        iplTeam: "KKR",
        fp: 383,
        bp: 1,
    },
    {
        name: "Kuldeep Yadav",
        country: "India",
        type: "Bowler",
        prevTeam: "Rishabh",
        iplTeam: "DC",
        fp: 399,
        bp: 1.5,
    },
    {
        name: "Mohammad Shami",
        country: "India",
        type: "Bowler",
        prevTeam: "Hardik",
        iplTeam: "GT",
        fp: 924,
        bp: 2,
    },
    {
        name: "Mohammad Siraj",
        country: "India",
        type: "Bowler",
        prevTeam: "Rishabh",
        iplTeam: "RCB",
        fp: 674,
        bp: 2,
    },
];
export default players;